services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: dockerfile
        ports:
            - 5173:5173
        volumes:
            - ../laravel-app:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/var/www
            - ./volumes/nginx/ssl:/etc/nginx/conf.d/ssl
            - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./volumes/nginx/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf
        depends_on:
            - php

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        image: mysql:8.1
        ports:
            - 3306:3306
        volumes:
            - ./volumes/logs:/var/log/mysql
            - ./volumes/db/data:/var/lib/mysql
            - ./volumes/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./volumes/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: refactorian
            MYSQL_USER: refactorian
            MYSQL_PASSWORD: refactorian

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - ./volumes/phpmyadmin/sessions:/sessions

    ####################################################################################################
    # Adminer
    ####################################################################################################
    adminer:
        image: adminer
        ports:
            - 9090:8080
        depends_on:
        - db

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail:
        image: axllent/mailpit:latest
        ports:
        - 8025:8025
        - 1025:1025

    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
        - ./volumes/redis/data:/data
        ports:
        - 6379:6379

    # ####################################################################################################
    # # Supervisord
    # ####################################################################################################
    # supervisord:
    #     image: supervisord
    #     build:
    #         context: ./volumes/supervisord
    #     volumes:
    #         - .:/var/www
    #         - ./volumes/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf
    #     depends_on:
    #         - php
    #         - nginx
    #         - db
    #         - redis
    #         - memcached
    #         - elasticsearch

    # ####################################################################################################
    # # Memcached
    # ####################################################################################################
    # memcached:
    #     image: memcached:latest
    #     ports:
    #         - 11211:11211

    # ####################################################################################################
    # # Elasticsearch
    # ####################################################################################################
    # elasticsearch:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    #     environment:
    #         - discovery.type=single-node
    #         - ES_JAVA_OPTS=-Xms512m -Xmx512m
    #     volumes:
    #         - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
    #     ports:
    #         - 9200:9200
    #         - 9300:9300
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1
